assets/objects/Maintance__c.object
<CustomObject>
    <fields>
        <fullName>Maintenance_Report__c</fullName>
        <label>Maintenance Report</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Maintenance_status__c</fullName>
        <label>Maintenance status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Maintained</fullName>
                </value>
                <value>
                    <fullName>Waiting _or_maintenance</fullName>
                    <default>true</default>
                    <label>Waiting for maintenance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Maintenances</relationshipLabel>
        <relationshipName>Maintenances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Maintenances</relationshipLabel>
        <relationshipName>Maintenances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Maintance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintance__c/fields/Maintenance_due_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_due_date__c</fullName>
    <label>Maintenance due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintance__c/fields/Maintenance_start_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_start_date__c</fullName>
    <label>Maintenance start date</label>
    <type>Date</type>
</CustomField>

assets/objects/Service__c.object
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Default_Service__c.field-meta.xml
<CustomField>
    <fullName>Default_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Service</label>
    <type>Checkbox</type>
</CustomField>

assets/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Last_Maintenance_Date__c</fullName>
        <label>Last Maintenance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Maintenance_Date__c</fullName>
        <label>Next Maintenance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plate_number__c</fullName>
        <externalId>true</externalId>
        <label>Plate number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Not Available</fullName>
                </value>
                <value>
                    <fullName>At Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VM_Controller.cls
public with sharing class VM_Controller {
    @AuraEnabled(cacheable=true)
    public static List<Vehicle__c> getVehicles() {
        return [SELECT Name, Status__c, Plate_Number__c, Model__c, Last_Maintenance_Date__c,
        Next_Maintenance_Date__c FROM Vehicle__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Vehicle__c> getVehiclesByStatus(String status) {
        status = status.trim();
        if(status == 'All') {
            return getVehicles();
        }
        return [SELECT Name, Status__c, Plate_Number__c, Model__c, Last_Maintenance_Date__c,
        Next_Maintenance_Date__c FROM Vehicle__c WHERE Status__c =: status];
    }

    @AuraEnabled(cacheable=true)
    public static List<Maintance__c> getRelatedMaintenances(Id vehicleId) {
        return [SELECT Name, Maintenance_start_date__c, Maintenance_due_date__c, Maintenance_Report__c,
        Maintenance_status__c, Service__r.Name FROM Maintance__c WHERE Vehicle__c =: vehicleId ORDER BY Name];
    }

    @AuraEnabled
    public static void insertMaintenance(Maintance__c maint){
        Service__c defaultService = [SELECT Name FROM Service__c WHERE Service__c.Default_Service__c = true LIMIT 1];
        if(maint.Service__c == null) {
            maint.Service__c = defaultService.Id;
        }
        try{  
            insert maint; 
        }catch(Exception e){
            System.debug('--->'+e);
        }
         System.debug('Con '+maint); 
    }   
}