assets/objects/Maintance__c.object
<CustomObject>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Maintenances</relationshipLabel>
        <relationshipName>Maintenances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Maintenances</relationshipLabel>
        <relationshipName>Maintenances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Maintance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintance__c/fields/Maintenance_due_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_due_date__c</fullName>
    <label>Maintenance due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintance__c/fields/Maintenance_start_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_start_date__c</fullName>
    <label>Maintenance start date</label>
    <type>Date</type>
</CustomField>

assets/objects/Service__c.object
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Default_Service__c.field-meta.xml
<CustomField>
    <fullName>Default_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Service</label>
    <type>Checkbox</type>
</CustomField>

assets/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Last_Maintenance_Date__c</fullName>
        <label>Last Maintenance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Vehicles (Last Service)</relationshipLabel>
        <relationshipName>Vehicles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Maintenance_Date__c</fullName>
        <label>Next Maintenance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plate_number__c</fullName>
        <externalId>true</externalId>
        <label>Plate number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Not Available</fullName>
                </value>
                <value>
                    <fullName>At Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Driver_Email__c.field-meta.xml
<CustomField>
    <fullName>Driver_Email__c</fullName>
    <formula>Driver__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Driver Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VehicleTriggerHelper.cls
public class VehicleTriggerHelper {
    public static final String STATUS_NOT_AVAILABLE = 'Not Available';
    public static final String STATUS_AT_SERVICE = 'At Service';
    public static final String STATUS_AVAILABLE = 'Available';
    public static final String VALIDATE_DATE_ERROR = 'Next maintenance date should be less than last.';
    
    public static void checkStatusAfterInsert(List<Vehicle__c> insertedVehicles) {
        List<Vehicle__c> notAvailableStatus = new List<Vehicle__c>();
        Map<String, String> emailsToSent =  new Map<String, String>();
        for(Vehicle__c item : notAvailableStatus) {
            if(item.Status__c == STATUS_AT_SERVICE || item.Status__c == STATUS_NOT_AVAILABLE) {
                emailsToSent.put(item.Driver_Email__c, ('Currently this vehicle is not available - '
                                                        + item.Plate_Number__c + ' ' + item.Model__c));
                notAvailableStatus.add(item);
            }
        }
        sendEmailToDrivers(emailsToSent);
    }
    public static void checkStatusAfterUpdate(Map<Id, Vehicle__c> vehiclesNewMap, Map<Id, Vehicle__c> vehiclesOldMap) {
        List<Vehicle__c> notAvailableStatus = new List<Vehicle__c>();
        Map<String, String> emailsToSent =  new Map<String, String>();
        for(Id vehicleId : vehiclesNewMap.keyset()) {
            Vehicle__c newValue = vehiclesNewMap.get(vehicleId);
            Vehicle__c oldValue = vehiclesOldMap.get(vehicleId);
            if(oldValue.Status__c == STATUS_AVAILABLE) {
                emailsToSent.put(newValue.Driver_Email__c, ('Currently this vehicle is not available - ' 
                                                            + newValue.Plate_Number__c + ' ' + newValue.Model__c));
                notAvailableStatus.add(newValue);
            }
        }
        sendEmailToDrivers(emailsToSent);
    }
    
    public static void checkNextMaintenanceDateInsert(List<Vehicle__c> insertedVehicles) {
        for(Vehicle__c item : insertedVehicles) {
            VehicleTriggerHelper.validateNextMaintenanceDate(item);
        }
    }
    
    public static void checkNextMaintenanceDateUpdate(Map<Id, Vehicle__c> vehiclesNewMap, Map<Id, Vehicle__c> vehiclesOldMap) {
        List<Vehicle__c> changedNextMaintenanceDate = new List<Vehicle__c>();
        for(Id vehicleId : vehiclesNewMap.keyset()) {
            VehicleTriggerHelper.validateNextMaintenanceDate(vehiclesNewMap.get(vehicleId));
            Vehicle__c newValue = vehiclesNewMap.get(vehicleId);
            Vehicle__c oldValue = vehiclesOldMap.get(vehicleId);
            if(oldValue.Next_Maintenance_Date__c != newValue.Next_Maintenance_Date__c) {
                changedNextMaintenanceDate.add(vehiclesNewMap.get(vehicleId));
            }
        }
        if(changedNextMaintenanceDate.size() > 0 ) {
            VehicleTriggerHelper.createNewMaintenanceRecords(changedNextMaintenanceDate);
        }
    }
    
    private static void validateNextMaintenanceDate(Vehicle__c vehicleItem) {
        if(vehicleItem.Next_Maintenance_Date__c < vehicleItem.Last_Maintenance_Date__c) {
            vehicleItem.Next_Maintenance_Date__c.addError(VALIDATE_DATE_ERROR);
        }
    }
    private static void sendEmailToDrivers(Map<String, String> emailsMap) {
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        for(String email : emailsMap.keySet()) {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            List<String> toAddresses = new List<String>();
            toAddresses.add(email);
            mail.setToAddresses(toAddresses);
            mail.setSubject(STATUS_NOT_AVAILABLE);
            mail.setPlainTextBody(emailsMap.get(email));
            mails.add(mail);
        }
        Messaging.sendEmail(mails);
    }
    private static void createNewMaintenanceRecords(List<Vehicle__c> records) {
        List<Maintance__c> newMaintenances = new List<Maintance__c>();
        Map<String, String> emailsToSent =  new Map<String, String>();
        Service__c defaultService = [SELECT Name FROM Service__c WHERE Service__c.Default_Service__c = true LIMIT 1];
        for(Vehicle__c vehicleItem : records) {
            List<Maintance__c> maint = new List<Maintance__c>();
            Maintance__c temp = new Maintance__c();
            temp.Maintenance_due_date__c = vehicleItem.Next_Maintenance_Date__c + 14;
            temp.Maintenance_start_date__c = vehicleItem.Next_Maintenance_Date__c;
            temp.Vehicle__c = vehicleItem.Id;
            if(vehicleItem.Last_Service__c == null) {
                temp.Service__c = defaultService.Id;
            } else {
                temp.Service__c = vehicleItem.Last_Service__c;
            }
            emailsToSent.put(vehicleItem.Driver_Email__c, ('New maintenance is scheduled for vehicle ' 
                                                           + vehicleItem.Plate_Number__c +  ' from ' +  temp.Maintenance_start_date__c
                                                           +  ' to ' + temp.Maintenance_due_date__c));
            
            newMaintenances.add(temp);
        }
        sendEmailToDrivers(emailsToSent);
        insert newMaintenances;
    }
}