assets/objects/Maintance__c.object
<CustomObject>
    <fields>
        <fullName>Scheduled_maintenance_date__c</fullName>
        <label>Scheduled maintenance date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Maintenances</relationshipLabel>
        <relationshipName>Maintenances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Maintenances</relationshipLabel>
        <relationshipName>Maintenances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Maintance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintance__c/fields/Maintenance_due_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_due_date__c</fullName>
    <label>Maintenance due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintance__c/fields/Maintenance_start_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_start_date__c</fullName>
    <label>Maintenance start date</label>
    <type>Date</type>
</CustomField>

assets/objects/Service__c.object
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Default_Service__c.field-meta.xml
<CustomField>
    <fullName>Default_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Service</label>
    <type>Checkbox</type>
</CustomField>

assets/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Driver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Driver</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Vehicles (Driver)</relationshipLabel>
        <relationshipName>Vehicles1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Maintenance_Date__c</fullName>
        <label>Last Maintenance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Maintenance_Date__c</fullName>
        <label>Next Maintenance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plate_number__c</fullName>
        <externalId>true</externalId>
        <label>Plate number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VehicleTriggerHandler_Test.cls
@isTest
public class VehicleTriggerHandler_Test {
    @TestSetup
    static void makeData() {
        List <Vehicle__c> vehicles = new List<Vehicle__c>();
        Contact driver = new Contact(LastName = 'Slava', Email = 'shegan782@gmail.com');
        Service__c defServ = new Service__c(Name = 'Nike', Default_Service__c = true);
        insert driver;
        insert defServ;
        for(Integer i = 0; i < 150; ++i) {
            vehicles.add(new Vehicle__c(Driver__c = driver.Id, Model__c = 'Mustang', Plate_number__c = 'TX2356',
                                        Last_Maintenance_Date__c = Date.today(),
                                        Next_Maintenance_Date__c = (Date.today() + 14)));
        }
        insert vehicles;
    }
    @isTest
    static void checkNewMaintanences() {
        List<Vehicle__c> testVehicles = [Select Next_Maintenance_Date__c From Vehicle__c Where Model__c = 'Mustang'];
        for(Vehicle__c vh : testVehicles) {
            vh.Next_Maintenance_Date__c = Date.today() + 3;
        }
        Test.startTest();
        update testVehicles;
        Test.stopTest();
        
        Vehicle__c updtVehicle = [Select Name, Next_Maintenance_Date__c From Vehicle__c Where Model__c = 'Mustang' Limit 1];
        Maintance__c testMaint = [Select Maintenance_due_date__c,
                                               Maintenance_start_date__c, Scheduled_maintenance_date__c,
                                               Service__c From Maintance__c Where Vehicle__r.Id =: updtVehicle.Id  Limit 1];
        System.assertEquals(updtVehicle.Next_Maintenance_Date__c + 14, testMaint.Maintenance_due_date__c);
        System.assertEquals(updtVehicle.Next_Maintenance_Date__c, testMaint.Maintenance_start_date__c);
        
    }
}