assets/objects/Maintance__c.object
<CustomObject>
    <fields>
        <fullName>Vehicle__c</fullName>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Maintenances</relationshipLabel>
        <relationshipName>Maintenances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Maintance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

assets/objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VM_Controller_Test.cls
@isTest
private class VM_Controller_Test {
    @isTest static void TestGetVehiclesByStatus() {
        List<Vehicle__c> insertedRecords = TestDataFactory.createVehiclesWithMaintenances(200, 5);
        
        Test.startTest();
        List<Vehicle__c> testVehiclesWithStatusAvailable = VM_Controller.getVehiclesByStatus('Available');
        List<Vehicle__c> testVehiclesAll = VM_Controller.getVehiclesByStatus('All');
        Test.stopTest();
        System.assertEquals(testVehiclesAll.size(), 200);
        System.assertEquals(insertedRecords.size(), testVehiclesWithStatusAvailable.size());
    }
    @isTest static void TestGetRelatedMaintenance() {
        List<Vehicle__c> insertedRecords = TestDataFactory.createVehiclesWithMaintenances(1, 5);
        Test.startTest();
        List<Vehicle__c> testVehicle = VM_Controller.getVehiclesByStatus('Available');
        List<Maintance__c> maintenances = VM_Controller.getRelatedMaintenances(testVehicle[0].Id);
        Test.stopTest();
        System.assertEquals(maintenances.size(), 5);
    }
}