assets/objects/Maintance__c.object
<CustomObject>
    <fields>
        <fullName>Maintenance_Report__c</fullName>
        <label>Maintenance Report</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Maintenance_status__c</fullName>
        <label>Maintenance status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Maintained</fullName>
                </value>
                <value>
                    <fullName>Waiting _or_maintenance</fullName>
                    <default>true</default>
                    <label>Waiting for maintenance</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Maintenances</relationshipLabel>
        <relationshipName>Maintenances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Maintenances</relationshipLabel>
        <relationshipName>Maintenances</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Maintance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintance__c/fields/Maintenance_due_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_due_date__c</fullName>
    <label>Maintenance due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintance__c/fields/Maintenance_start_date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_start_date__c</fullName>
    <label>Maintenance start date</label>
    <type>Date</type>
</CustomField>

assets/objects/Service__c.object
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Default_Service__c.field-meta.xml
<CustomField>
    <fullName>Default_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Service</label>
    <type>Checkbox</type>
</CustomField>

assets/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Last_Maintenance_Date__c</fullName>
        <label>Last Maintenance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Maintenance_Date__c</fullName>
        <label>Next Maintenance Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plate_number__c</fullName>
        <externalId>true</externalId>
        <label>Plate number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Not Available</fullName>
                </value>
                <value>
                    <fullName>At Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static List<Vehicle__c> createVehiclesWithMaintenances(Integer numVehicles, Integer numMaint) {
        List<Vehicle__c> vehicles = new List<Vehicle__c>();
        Service__c defServ = new Service__c(Name = 'Nike', Default_Service__c = true);
        insert defServ;
        for(Integer i=0; i < numVehicles; i++) {
            Vehicle__c a = new Vehicle__c(Status__c='Available',
                Model__c = 'Mustang', Plate_number__c = 'TX2356',
                Last_Maintenance_Date__c = Date.today(),
                Next_Maintenance_Date__c = (Date.today() + 14));
            vehicles.add(a);
        }
        insert vehicles;
        
        List<Maintance__c> maints = new List<Maintance__c>();
        for (Integer j = 0; j < numVehicles; j++) {
            Vehicle__c vehicle = vehicles[j];
            for (Integer k = 0; k < numMaint; k++) {
                maints.add(new Maintance__c(Vehicle__c=vehicle.Id,
                    Maintenance_start_date__c=(Date.today() + 14),
                    Maintenance_due_date__c=(Date.today() + 28),
                    Maintenance_Report__c='Test Report',
                    Maintenance_status__c='Maintained',
                    Service__c=defServ.Id));
            }
        }
        insert maints;
        
        return vehicles;
    }
}